name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  test:
    name: "Test: Python ${{ matrix.python }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install cleanlab
        run: pip install -e .
      - name: Check cleanlab runs without optional dependencies
        run: python3 -c "import cleanlab"
      - name: Install development dependencies
        run: pip install -r requirements-dev.txt
      - name: Overwrite tensorflow version on Windows
        if: matrix.os == 'windows-latest'
        run: |
          pip uninstall -y tensorflow
          pip install tensorflow-cpu
      - name: Test with coverage
        run: pytest --verbose --cov=cleanlab/ --cov-config .coveragerc --cov-report=xml
      - uses: codecov/codecov-action@v2
  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .  # install dependencies
          pip install -r requirements-dev.txt  # install development dependencies and type stubs
      - name: Type check
        run: mypy --install-types --non-interactive --allow-redefinition cleanlab
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
  pylint:
    name: Check for unused/wildcard imports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pylint
        run: pip install pylint
      - name: Error on unused imports
        run: pylint --disable=all --enable=unused-import cleanlab tests
      - name: Error on wildcard imports
        run: pylint --disable=all --enable=wildcard-import cleanlab tests
  nblint:
    name: Lint Notebooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: nblint
        run: ./.ci/nblint.py docs
